apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: {{ .Values.namespaceName }}
  labels: 
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80