FROM centos:8
RUN yum update -y
RUN yum install openssl-devel gcc pcre-devel automake autoconf libtool make -y
RUN rpm -qa|egrep 'openssl-devel|pcre|zlib'
RUN mkdir -p /web/nginx
RUN mkdir /web/nginx/modules
RUN mkdir /web/nginx/run
# install nodejs
RUN yum install epel-release -y
RUN yum install nodejs -y
WORKDIR /web/nginx/
ADD http://nginx.org/download/nginx-1.21.1.tar.gz .
RUN tar  -xzvf  nginx-1.21.1.tar.gz
RUN mkdir binaries 
RUN mv nginx-1.21.1/* binaries/
RUN rm  -rf nginx-1.21.1/
WORKDIR /web/nginx/binaries
ADD https://github.com/vkholodkov/nginx-upload-module/archive/refs/heads/master.zip .
RUN yum install zip -y
RUN unzip master.zip
RUN ./configure --prefix=/web/nginx --modules-path=/web/nginx/modules --with-http_ssl_module  --without-http_fastcgi_module --without-http_uwsgi_module --without-http_grpc_module --without-http_scgi_module --without-mail_imap_module --without-mail_pop3_module --add-module=nginx-upload-module-master
RUN make
RUN make install
WORKDIR /web/nginx/
RUN rm -rf binaries/
WORKDIR /web/nginx/conf
RUN mkdir /web/nginx/conf/conf.d
RUN mkdir /var/log/nginx/
COPY ./nginx.conf /web/nginx/conf/
COPY ./default.conf /web/nginx/conf/conf.d
COPY ./rename.js /web/
WORKDIR /web/nginx/sbin
CMD  ./nginx; node /web/rename.js 